### ISSUE TITLE
提示找不到config.properties？

### ISSUE THREAD

**Issue by rzjc** [MoeGrid/ssrpanel-v2ray#3]
java -jar /root/ssrpanel-v2ray/ssrpanel-v2ray-0.0.2.jar
  __  __ _           _           _   _      _
 |  \/  (_)___  __ _| | ____ _  | \ | | ___| |_
 | |\/| | / __|/ _` | |/ / _` | |  \| |/ _ \ __|
 | |  | | \__ \ (_| |   < (_| | | |\  |  __/ |_
 |_|  |_|_|___/\__,_|_|\_\__,_| |_| \_|\___|\__|

2018/10/28 18:46:04 [ERROR] cn.moegezi.v2ray.node.utils.ConfigUtil: 配置文件错误
org.apache.commons.configuration2.ex.ConfigurationException: Could not locate: org.apache.commons.configuration2.io.FileLocator@2133c8f8[fileName=config.properties,basePath=<null>,sourceURL=,encoding=ISO-8859-1,fileSystem=<null>,locationStrategy=<null>]
        at org.apache.commons.configuration2.io.FileLocatorUtils.locateOrThrow(FileLocatorUtils.java:346)
        at org.apache.commons.configuration2.io.FileHandler.load(FileHandler.java:972)
        at org.apache.commons.configuration2.io.FileHandler.load(FileHandler.java:702)
        at org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder.initFileHandler(FileBasedConfigurationBuilder.java:312)
        at org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder.initResultInstance(FileBasedConfigurationBuilder.java:291)
        at org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder.initResultInstance(FileBasedConfigurationBuilder.java:60)
        at org.apache.commons.configuration2.builder.BasicConfigurationBuilder.createResult(BasicConfigurationBuilder.java:421)
        at org.apache.commons.configuration2.builder.BasicConfigurationBuilder.getConfiguration(BasicConfigurationBuilder.java:285)
        at cn.moegezi.v2ray.node.utils.ConfigUtil.<clinit>(ConfigUtil.java:24)
        at cn.moegezi.v2ray.node.process.V2rayManager.<init>(V2rayManager.java:11)
        at cn.moegezi.v2ray.node.process.V2rayManager.getInstance(V2rayManager.java:39)
        at cn.moegezi.v2ray.node.V2rayNodeApp.main(V2rayNodeApp.java:15)
Exception in thread "main" java.lang.NullPointerException
        at cn.moegezi.v2ray.node.utils.ConfigUtil.getString(ConfigUtil.java:31)
        at cn.moegezi.v2ray.node.process.V2rayManager.<init>(V2rayManager.java:11)
        at cn.moegezi.v2ray.node.process.V2rayManager.getInstance(V2rayManager.java:39)
        at cn.moegezi.v2ray.node.V2rayNodeApp.main(V2rayNodeApp.java:15)

**Comment by rzjc** [comment]
digitalocean的CENTOS7.5

**Comment by rzjc** [comment]
编译运行就正常，下载release就那样提示

**Comment by MoeGrid** [comment]
config.properties 没和 jar文件放在一起

**Comment by rzjc** [comment]
> config.properties 没和 jar文件放在一起

放一起了
