### ISSUE TITLE
dalao,遇到这个问题是什么原因呢

### ISSUE THREAD

**Issue by Helpayment** [MoeGrid/ssrpanel-v2ray#8]
[root@VM_81_0_centos ssrpanel-v2ray]# java -jar ssrpanel-v2ray-0.0.2.jar
  __  __ _           _           _   _      _
 |  \/  (_)___  __ _| | ____ _  | \ | | ___| |_
 | |\/| | / __|/ _` | |/ / _` | |  \| |/ _ \ __|
 | |  | | \__ \ (_| |   < (_| | | |\  |  __/ |_
 |_|  |_|_|___/\__,_|_|\_\__,_| |_| \_|\___|\__|

V2Ray 3.49 (die Commanderin) 20181025
A unified platform for anti-censorship.
2018/10/30 21:20:50 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已启动  
Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 10087 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:10087 > listen tcp 0.0.0.0:10087: bind: address already in use
2018/10/30 21:20:50 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...  
2018/10/30 21:20:51 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Start completed.  
2018/10/30 21:20:51 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已停止  
2018/10/30 21:20:51 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
2018/10/30 21:20:51 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.17 0.18 0.15  
2018/10/30 21:20:51 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked  
2018/10/30 21:20:51 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked  
2018/10/30 21:20:51 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked  
2018/10/30 21:20:51 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked  
2018/10/30 21:20:51 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked  
2018/10/30 21:20:51 [ERROR] cn.moegezi.v2ray.node.process.V2rayGrpc: 添加用户失败io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked  
2018/10/30 21:20:51 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 更新用户: ADD 6 REMOVE 0

**Comment by MoeGrid** [comment]
listen tcp 0.0.0.0:10087: bind: address already in use
10087端口被占用

**Comment by Helpayment** [comment]
大佬，您看这个报错又是什么原因呢
V2Ray 3.49 (die Commanderin) 20181025
A unified platform for anti-censorship.
2018/11/04 00:18:57 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已启动  
2018/11/04 00:18:57 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...  
2018/11/04 00:18:58 [INFO] com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Start completed.  
2018/11/04 00:18:58 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 0  
2018/11/04 00:18:59 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.00 0.01 0.05  
2018/11/04 00:18:59 [ERROR] cn.moegezi.v2ray.node.process.V2rayDao: 更新用户异常  
java.sql.SQLException: Unknown column 'vmess_id' in 'field list' Query: SELECT id, vmess_id vmessId FROM user WHERE enable = 1 AND u + d < transfer_enable Parameters: []
	at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:527)
	at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:391)
	at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:347)
	at cn.moegezi.v2ray.node.process.V2rayDao.getAllUser(V2rayDao.java:117)
	at cn.moegezi.v2ray.node.process.V2rayGrpc.syncUser(V2rayGrpc.java:92)
	at cn.moegezi.v2ray.node.process.V2rayGrpc.update(V2rayGrpc.java:88)
	at cn.moegezi.v2ray.node.process.V2rayTimingThread.run(V2rayTimingThread.java:29)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018/11/04 00:18:59 [ERROR] cn.moegezi.v2ray.node.process.V2rayTimingThread: 定时任务异常  
java.lang.NullPointerException
	at cn.moegezi.v2ray.node.process.V2rayGrpc.syncUser(V2rayGrpc.java:104)
	at cn.moegezi.v2ray.node.process.V2rayGrpc.update(V2rayGrpc.java:88)
	at cn.moegezi.v2ray.node.process.V2rayTimingThread.run(V2rayTimingThread.java:29)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:114

**Comment by MoeGrid** [comment]
ssrpanel没有更新，数据库没有vmess_id字段
