### ISSUE TITLE
服务端开了一天，报错了

### ISSUE THREAD

**Issue by WankkoRee** [MoeGrid/ssrpanel-v2ray#9]
2018/11/05 01:38:11开启的
```
2018/11/05 12:16:13 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 获取用户流量: USER user>>>1@v2ray.com>>>traffic>>>uplink TRAFFIC 221174  
2018/11/05 12:16:13 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 获取用户流量: USER user>>>1@v2ray.com>>>traffic>>>downlink TRAFFIC 1361152  
2018/11/05 12:16:13 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 获取用户流量: USER user>>>2@v2ray.com>>>traffic>>>uplink TRAFFIC 0  
2018/11/05 12:16:13 [INFO] cn.moegezi.v2ray.node.process.V2rayGrpc: 获取用户流量: USER user>>>2@v2ray.com>>>traffic>>>downlink TRAFFIC 0  
2018/11/05 12:16:13 [ERROR] cn.moegezi.v2ray.node.process.V2rayDao: 记录流量日志: USER_NUM 1 ALL_TRAFFIC 1545.24KB  
2018/11/05 12:16:13 [ERROR] cn.moegezi.v2ray.node.process.V2rayDao: 更新用户流量信息: USER_NUM 1  
2018/11/05 12:16:13 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新在线用户数: NUMBER 1  
2018/11/05 12:16:13 [INFO] cn.moegezi.v2ray.node.process.V2rayDao: 更新节点负载信息: LOAD 0.01 0.01 0.00  
```
最后一次成功的记录↑
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2a pc=0x75bc76]

goroutine 30815 [running]:
v2ray.com/core/common/mux.(*Session).NewReader(0x0, 0xc000970ab0, 0xbea7a0, 0x10bc1ed)
	/v2/src/v2ray.com/core/common/mux/session.go:148 +0x26
v2ray.com/core/common/mux.(*ServerWorker).handleStatusKeep(0xc00069a940, 0xc000bacaa0, 0xc000970ab0, 0x0, 0x0)
	/v2/src/v2ray.com/core/common/mux/server.go:148 +0x82
v2ray.com/core/common/mux.(*ServerWorker).handleFrame(0xc00069a940, 0xbf4e60, 0xc0009708d0, 0xc000970ab0, 0x0, 0x0)
	/v2/src/v2ray.com/core/common/mux/server.go:192 +0x210
v2ray.com/core/common/mux.(*ServerWorker).run(0xc00069a940, 0xbf4e60, 0xc0009708d0)
	/v2/src/v2ray.com/core/common/mux/server.go:215 +0x111
created by v2ray.com/core/common/mux.(*Server).Dispatch
	/v2/src/v2ray.com/core/common/mux/server.go:55 +0x2f4
2018/11/05 12:17:03 [INFO] cn.moegezi.v2ray.node.process.V2rayDestroyer: V2ray已停止  
```
接下去就是v2ray报错，然后服务端也跟着关闭了。

**Comment by WankkoRee** [comment]
好像是mux多路复用的锅，能不能解决一下，我客户端这边关掉mux就行了

**Comment by MoeGrid** [comment]
这是v2ray报的错，和节点端并没有什么关系
